IIIProject_MVC_Travel/IIIProject_travel/Controllers/優惠發送Controller.cs
using IIIProject_travel.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace IIIProject_travel.Controllers
{
    public class 優惠發送Controller : Controller
    {
        // GET: 優惠發送
        public ActionResult List()
        {
            return View();
        }

        [HttpPost]
        public ActionResult List(string randLocation)
        {

            dbJoutaEntities db = new dbJoutaEntities();

            var x = (from t in db.tMember
                     //where (t.f會員緯度 < curLat+0.02 && 
                     //t.f會員緯度 > curLat - 0.02 &&
                     //t.f會員經度 < curLng + 0.02 &&
                     //t.f會員經度 > curLng - 0.02)
                     select new
                     {
                         mMemberNum = t.f會員編號,
                         mEmail = t.f會員電子郵件,
                         mName = t.f會員名稱,
                         mRating = t.f會員評分
                     })
                    .OrderBy(t => Guid.NewGuid()).Take(1);

            return Json(x, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SendMail(string txtCouponInfo, string memberId1)
        {
            dbJoutaEntities db = new dbJoutaEntities();

            var x = db.tMember.Where(a => a.f會員帳號 == memberId1.ToString()).FirstOrDefault();

            string randCode = Guid.NewGuid().ToString();

            //Jouta官方帳號
            string gmail_account = "Joutagroup445@gmail.com";
            string gmail_password = "admin123admin";
            string gmail_mail = "Joutagroup445@gmail.com";     //gmail信箱

            //var verifyUrl = "/Home/ResetPassword/" + randCode;
            //var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress(gmail_mail, "Jouta服務團隊");
            var toEmail = new MailAddress(x.f會員電子郵件);
            string body = "您好，<br/><br/>恭喜您抽到：" + txtCouponInfo +
            "<br/><br/>優惠代碼請至該店家網站或其門市兌換使用：" + randCode + "，使用期限至9/30，請盡速使用!</a>";

            SmtpClient smtpServer = new SmtpClient("smtp.gmail.com");
            smtpServer.Port = 587;
            smtpServer.Credentials = new System.Net.NetworkCredential(gmail_account, gmail_password);
            //開啟SSL
            smtpServer.EnableSsl = true;

            MailMessage mail = new MailMessage();
            //設定來源信箱
            mail.From = new MailAddress(gmail_mail);
            //設定收信者信箱
            mail.To.Add(toEmail);
            //主旨
            mail.Subject = "Jouta 優惠好禮 !";
            //內容
            mail.Body = body;
            //設定信箱內容為HTML格式
            mail.IsBodyHtml = true;
            smtpServer.Send(mail);

            return RedirectToAction("List");
        }
    }
}

IIIProject_MVC_Travel/IIIProject_travel/Controllers/後台文章Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace IIIProject_travel.Controllers
{
    public class 後台文章Controller : Controller
    {
        // GET: 後台文章
        public ActionResult List(string date起日, string dateStartFilter, string date迄日, string dateEndFiler, string sortOrder, string txt關鍵字, string currentFilter, int page = 1)
        {

            //搜尋
            var 文章 = from m in (new dbJoutaEntities()).tActivity
                     where m.f活動類型 == "文章"
                     select m;

            if (txt關鍵字 != null && date起日 != null && date迄日 != null)
            {
                page = 1;
            }
            else
            {
                txt關鍵字 = currentFilter;
                date起日 = dateStartFilter;
                date迄日 = dateEndFiler;
            }

            if (string.IsNullOrEmpty(txt關鍵字))
            {
                文章 = from m in (new dbJoutaEntities()).tActivity
                     where m.f活動類型 == "文章"
                     select m;
                if (!string.IsNullOrEmpty(date起日) && !string.IsNullOrEmpty(date迄日))
                    文章 = from p in 文章
                         where (string.Compare(p.f活動發起日期.Substring(0, 10), date起日) >= 0) &&
                               (string.Compare(p.f活動發起日期.Substring(0, 10), date迄日) <= 0)
                         select p;
            }

            else
            {
                文章 = from m in 文章
                     where m.f活動類型.Contains("文章") &&
                            (string.Compare(m.f活動發起日期.Substring(0, 10), date起日) >= 0) &&
                            (string.Compare(m.f活動發起日期.Substring(0, 10), date迄日) <= 0) &&
                           m.f活動編號.ToString().Contains(txt關鍵字) || m.f活動標題.Contains(txt關鍵字) ||
                           m.f活動標籤.Contains(txt關鍵字) || m.f活動內容.Contains(txt關鍵字) ||
                           m.f活動團圖.Contains(txt關鍵字) || m.f活動地區.Contains(txt關鍵字) ||
                           m.f活動地點.Contains(txt關鍵字) || m.f活動所屬.Contains(txt關鍵字) ||
                           m.f活動招募截止時間.Contains(txt關鍵字) || m.f活動分類.Contains(txt關鍵字) ||
                           m.f活動留言.Contains(txt關鍵字) || m.f活動留言時間.Contains(txt關鍵字) ||
                           m.f活動發起日期.Contains(txt關鍵字) || m.f活動結束時間.Contains(txt關鍵字) ||
                           m.f活動開始時間.Contains(txt關鍵字)
                     select m;
            }

            //排序 降冪和升冪
            ViewBag.當前搜尋 = txt關鍵字;
            ViewBag.當前起日 = date起日;
            ViewBag.當前迄日 = date迄日;
            ViewBag.標題排序 = string.IsNullOrEmpty(sortOrder) ? "標題降冪" : "";
            ViewBag.編號排序 = sortOrder == "編號升冪" ? "編號降冪" : "編號升冪";
            ViewBag.帳號排序 = sortOrder == "帳號升冪" ? "帳號降冪" : "帳號升冪";
            ViewBag.內容排序 = sortOrder == "內容升冪" ? "內容降冪" : "內容升冪";
            ViewBag.建立時間排序 = sortOrder == "建立時間升冪" ? "建立時間降冪" : "建立時間升冪";
            ViewBag.地區排序 = sortOrder == "地區升冪" ? "地區降冪" : "地區升冪";

            switch (sortOrder)
            {
                case "標題降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動標題);
                    break;
                case "編號降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動編號);
                    break;
                case "編號升冪":
                    文章 = 文章.OrderBy(s => s.f活動編號);
                    break;
                case "帳號降冪":
                    文章 = 文章.OrderByDescending(s => s.f會員編號);
                    break;
                case "帳號升冪":
                    文章 = 文章.OrderBy(s => s.f會員編號);
                    break;
                case "內容降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動內容);
                    break;
                case "內容升冪":
                    文章 = 文章.OrderBy(s => s.f活動內容);
                    break;
                case "建立時間降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動發起日期);
                    break;
                case "建立時間升冪":
                    文章 = 文章.OrderBy(s => s.f活動發起日期);
                    break;
                case "地區降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動地區);
                    break;
                case "地區升冪":
                    文章 = 文章.OrderBy(s => s.f活動地區);
                    break;

                default:
                    文章 = 文章.OrderBy(s => s.f活動標題);
                    break;
            }



            //分頁
            int 筆數 = 20;
            int 當前頁面 = page < 1 ? 1 : page;
            var 結果 = 文章.ToPagedList(當前頁面, 筆數);

            return View(結果);
        }



        public ActionResult d刪除(int? id)
        {
            if (id == null)
                RedirectToAction("List");

            tActivity x = new tActivity();
            dbJoutaEntities db = new dbJoutaEntities();
            x = db.tActivity.FirstOrDefault(m => m.f活動編號 == id);
            db.tActivity.Remove(x);
            db.SaveChanges();

            return RedirectToAction("List");

        }
        public ActionResult v查看(int? id)
        {
            if (id == null)
                RedirectToAction("List");

            dbJoutaEntities db = new dbJoutaEntities();
            tActivity x = new tActivity();
            x = db.tActivity.FirstOrDefault(m => m.f活動編號 == id);

            return View(x);
        }


    }
}

IIIProject_MVC_Travel/IIIProject_travel/Controllers/後台飯局Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace IIIProject_travel.Controllers
{
    public class 後台飯局Controller : Controller
    {
        // GET: 後台飯局
        public ActionResult List(string date起日, string dateStartFilter, string date迄日, string dateEndFiler, string sortOrder, string txt關鍵字, string currentFilter, int page = 1)
        {

            //搜尋
            //IQueryable<tActivity> 飯局 = null;
            var 飯局 = from m in (new dbJoutaEntities()).tActivity
                     where m.f活動類型 == "飯局"
                     select m;


            if (txt關鍵字 != null && date起日 != null && date迄日 != null)
            {
                page = 1;
            }
            else
            {
                txt關鍵字 = currentFilter;
                date起日 = dateStartFilter;
                date迄日 = dateEndFiler;
            }


            if (string.IsNullOrEmpty(txt關鍵字))
            {
                飯局 = from m in (new dbJoutaEntities()).tActivity
                     where m.f活動類型 == "飯局"
                     select m;
                if (!string.IsNullOrEmpty(date起日) && !string.IsNullOrEmpty(date迄日))
                飯局 = from p in 飯局
                     where (string.Compare(p.f活動發起日期.Substring(0, 10), date起日) >= 0) && 
                           (string.Compare(p.f活動發起日期.Substring(0, 10), date迄日) <= 0)
                     select p;
            }

            else
            {

                飯局 = from m in 飯局
                     where m.f活動類型.Contains("飯局") &&
                           (string.Compare(m.f活動發起日期.Substring(0, 10), date起日) >= 0) && 
                           (string.Compare(m.f活動發起日期.Substring(0, 10), date迄日) <= 0) &&
                           m.f活動編號.ToString().Contains(txt關鍵字) || m.f活動標題.Contains(txt關鍵字) ||
                           m.f活動標籤.Contains(txt關鍵字) || m.f活動內容.Contains(txt關鍵字) ||
                           m.f活動團圖.Contains(txt關鍵字) || m.f活動地區.Contains(txt關鍵字) ||
                           m.f活動地點.Contains(txt關鍵字) || m.f活動所屬.Contains(txt關鍵字) ||
                           m.f活動招募截止時間.Contains(txt關鍵字) || m.f活動分類.Contains(txt關鍵字) ||
                           m.f活動留言.Contains(txt關鍵字) || m.f活動留言時間.Contains(txt關鍵字) ||
                           m.f活動發起日期.Contains(txt關鍵字) || m.f活動結束時間.Contains(txt關鍵字) ||
                           m.f活動開始時間.Contains(txt關鍵字)
                     select m;

            }


            //排序 降冪和升冪
            ViewBag.當前搜尋 = txt關鍵字;
            ViewBag.當前起日 = date起日;
            ViewBag.當前迄日 = date迄日;
            ViewBag.標題排序 = string.IsNullOrEmpty(sortOrder) ? "標題降冪" : "";
            ViewBag.編號排序 = sortOrder == "編號升冪" ? "編號降冪" : "編號升冪";
            ViewBag.帳號排序 = sortOrder == "帳號升冪" ? "帳號降冪" : "帳號升冪";
            ViewBag.內容排序 = sortOrder == "內容升冪" ? "內容降冪" : "內容升冪";
            ViewBag.點讚排序 = sortOrder == "點讚升冪" ? "點讚降冪" : "點讚升冪";
            ViewBag.建立時間排序 = sortOrder == "建立時間升冪" ? "建立時間降冪" : "建立時間升冪";
            ViewBag.招募截止時間排序 = sortOrder == "招募截止時間升冪" ? "招募截止時間降冪" : "招募截止時間升冪";
            ViewBag.開始時間排序 = sortOrder == "開始時間升冪" ? "開始時間降冪" : "開始時間升冪";
            ViewBag.結束時間排序 = sortOrder == "結束時間升冪" ? "結束時間降冪" : "結束時間升冪";
            ViewBag.地區排序 = sortOrder == "地區升冪" ? "地區降冪" : "地區升冪";
            ViewBag.地點排序 = sortOrder == "地點升冪" ? "地點降冪" : "地點升冪";
            ViewBag.預算排序 = sortOrder == "預算升冪" ? "預算降冪" : "預算升冪";
            ViewBag.分類排序 = sortOrder == "分類升冪" ? "分類降冪" : "分類升冪";

            switch (sortOrder)
            {
                case "標題降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動標題);
                    break;
                case "編號降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動編號);
                    break;
                case "編號升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動編號);
                    break;
                case "帳號降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f會員編號);
                    break;
                case "帳號升冪":
                    飯局 = 飯局.OrderBy(s => s.f會員編號);
                    break;
                case "內容降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動內容);
                    break;
                case "內容升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動內容);
                    break;
                case "點讚降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動讚數);
                    break;
                case "點讚升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動讚數);
                    break;
                case "建立時間降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動發起日期);
                    break;
                case "建立時間升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動發起日期);
                    break;
                case "招募截止時間降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動招募截止時間);
                    break;
                case "招募截止時間升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動招募截止時間);
                    break;
                case "開始時間降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動開始時間);
                    break;
                case "開始時間升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動開始時間);
                    break;
                case "結束時間降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動結束時間);
                    break;
                case "結束時間升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動結束時間);
                    break;
                case "地區降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動地區);
                    break;
                case "地區升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動地區);
                    break;
                case "地點降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動地點);
                    break;
                case "地點升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動地點);
                    break;
                case "預算降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動預算);
                    break;
                case "預算升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動預算);
                    break;
                case "分類降冪":
                    飯局 = 飯局.OrderByDescending(s => s.f活動分類);
                    break;
                case "分類升冪":
                    飯局 = 飯局.OrderBy(s => s.f活動分類);
                    break;

                default:
                    飯局 = 飯局.OrderBy(s => s.f活動標題);
                    break;
            }



            //分頁
            int 筆數 = 20;
            int 當前頁面 = page < 1 ? 1 : page;
            var 結果 = 飯局.ToPagedList(當前頁面, 筆數);

            return View(結果);
        }

        public ActionResult d刪除(int? id)
        {
            if (id == null)
                RedirectToAction("List");

            tActivity x = new tActivity();
            dbJoutaEntities db = new dbJoutaEntities();
            x = db.tActivity.FirstOrDefault(m => m.f活動編號 == id);
            db.tActivity.Remove(x);
            db.SaveChanges();

            return RedirectToAction("List");

        }
        public ActionResult v查看(int? id)
        {
            if (id == null)
                RedirectToAction("List");

            dbJoutaEntities db = new dbJoutaEntities();
            tActivity x = new tActivity();
            x = db.tActivity.FirstOrDefault(m => m.f活動編號 == id);

            return View(x);

        }


    }
}

IIIProject_MVC_Travel/IIIProject_travel/Views/後台飯局/List.cshtml
@using PagedList
@using PagedList.Mvc

@{
    Layout = null;
}
@model IPagedList<IIIProject_travel.tActivity>

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="">
    <title>飯局列表 | Jouta Admin</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/Content/css/dashboard.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
        }

        #line {
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 300px;
            white-space: nowrap;
        }

        #line1 {
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 200px;
            white-space: nowrap;
        }

        .table td, .table th {
            vertical-align: middle;
        }
    </style>

</head>

<body>

    @*navbar*@
    <form action="/後台飯局/List" method="GET">
        <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="@Url.Action("Home","後台Home")">
                <img src="~/Content/images/joutalogo.png" width="14" class="mr-2" />Jouta Admin
            </a>
            <div>
                <span class="badge badge-secondary">建立起日：</span>
                <input type="date" name="date起日" />
            </div>
            <div>
                <span class="badge badge-secondary">建立迄日：</span>
                <input type="date" name="date迄日" />
            </div>
            <input type="text" placeholder="關鍵字" aria-label="Search" name="txt關鍵字" class="form-control form-control-dark w-100">
            <input type="submit" value="搜尋" class=" btn btn-secondary" />
            <ul class="navbar-nav px-3">
                <li class="nav-item text-nowrap">
                    <a>
                        @Html.ActionLink("Sign out", "Home", "Home", new { id = 0 }, new { @class = "nav-link" })
                    </a>
                </li>
            </ul>
        </nav>
    </form>

    @*sidebar*@
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Home","後台Home")">
                                <span data-feather="home"></span>
                                網站概覽
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","後台會員")">
                                <span data-feather="users"></span>
                                會員列表
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","後台旅遊")">
                                <span data-feather="file"></span>
                                旅遊列表
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","後台飯局")">
                                <span data-feather="bar-chart-2"></span>
                                飯局列表　<
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","後台文章")">
                                <span data-feather="layers"></span>
                                文章列表
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","聯絡我們")">
                                <span data-feather="message-square"></span>
                                意見列表
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","優惠發送")">
                                <span data-feather="gift"></span>
                                優惠發送
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            @*主內容*@
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

                <h2>飯局列表</h2>
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <td>@Html.ActionLink("編號", "List", new { sortOrder = ViewBag.編號排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("帳號", "List", new { sortOrder = ViewBag.帳號排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("標題", "List", new { sortOrder = ViewBag.標題排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("內容", "List", new { sortOrder = ViewBag.內容排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("點讚", "List", new { sortOrder = ViewBag.點讚排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("建立時間", "List", new { sortOrder = ViewBag.建立時間排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("招募截止時間", "List", new { sortOrder = ViewBag.招募截止時間排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("開始時間", "List", new { sortOrder = ViewBag.開始時間排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("結束時間", "List", new { sortOrder = ViewBag.結束時間排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("地點", "List", new { sortOrder = ViewBag.地點排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("地區", "List", new { sortOrder = ViewBag.地區排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("預算", "List", new { sortOrder = ViewBag.預算排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("分類", "List", new { sortOrder = ViewBag.分類排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>按鈕</td>
                                <td>按鈕</td>

                            </tr>
                        </thead>

                        <tbody>

                            @{
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.f活動編號)</td>
                                        <td>@Html.DisplayFor(modelItem => item.tMember.f會員名稱)</td>
                                        <td id="line1">@Html.DisplayFor(modelItem => item.f活動標題)</td>
                                        <td id="line">@Html.DisplayFor(modelItem => item.f活動內容)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動讚數)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動發起日期).ToString().Substring(0, 10)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動招募截止時間)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動開始時間)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動結束時間)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動地點)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動地區)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動預算)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f活動分類)</td>
                                        <td>
                                            @Html.ActionLink("查看", "v查看", "後台飯局", new { id = item.f活動編號 }, new { Class = "btn btn-info" })
                                        </td>
                                        <td>
                                            @Html.ActionLink("刪除", "d刪除", "後台飯局", new { id = item.f活動編號 },
                                           new { OnClick = "return confirm('確定要刪除嗎?')", Class = "btn btn-danger" })
                                        </td>
                                    </tr>
                                }
                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("List", new { page }))
                </div>
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="~/Scripts/jquery-slim.min.js"><\/script>')</script>
    <script src="~/Content/bootstrap-4.5.2-dist/js/bootstrap.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="~/Scripts/IIIProject/dashboard.js"></script>
</body>

</html>