IIIProject_MVC_Travel/IIIProject_travel/Controllers/BlogController.cs
using IIIProject_travel.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Compilation;
using System.Web.Mvc;
using System.Drawing;
using System.Drawing.Imaging;
using ZXing;
using ZXing.QrCode;
using PagedList;

namespace IIIProject_travel.Controllers
{
    public class BlogController : Controller
    {

        dbJoutaEntities db = new dbJoutaEntities();
        int pagesize = 3;
        // GET: Blog

        public ActionResult Index(string sortOder,string txtKey, string currentfilter, int page = 1)
        {
            var article = from t in (new dbJoutaEntities()).tActivity
                          where t.f活動類型 == "文章"
                          orderby t.f活動發起日期 
                          select t;

            //IQueryable<tActivity> tarticle = null;

            if (txtKey != null)
            {
                page = 1;
            }
            else
            {
                txtKey = currentfilter;
            }

            if (string.IsNullOrEmpty(txtKey))
            {
                article = article.OrderBy(s => s.f活動發起日期);
            }
                
            else
            {

                    article = from m in (new dbJoutaEntities()).tActivity
                           where m.f活動類型 == "文章" && m.f活動標題.Contains(txtKey)
                           orderby m.f活動發起日期 
                           select m;


            }
                
            ViewBag.Sernow = txtKey;
            //ViewBag.keyName = string.IsNullOrEmpty(sortOder) ? "NameDown" : "";
            ViewBag.dateOrder = sortOder == "dateUp" ? "dateDown" : "dateUp";
            ViewBag.preViewOrder = sortOder == "preViewUp" ? "preViewDown" : "preViewUp";
            ViewBag.LikeOrder = sortOder == "LikeUp" ? "LikeDown" : "LikeUp";
            //ViewBag.Pointorder = sortOder == "帳號升冪" ? "帳號降冪" : "帳號升冪";



            switch (sortOder)
            {
                case null:
                    article = article.OrderByDescending(s => s.f活動發起日期);
                    break;

                case "NameDown":
                    article = article.OrderByDescending(s => s.f活動標題);
                    break;

                case "dateUp":
                    article = article.OrderBy(s => s.f活動發起日期);
                    break;
                case "dateDown":
                    article = article.OrderByDescending(s => s.f活動發起日期);
                    break;
                case "preViewUp":
                    article = article.OrderBy(s => s.f活動瀏覽次數);
                    break;
                case "preViewDown":
                    article = article.OrderByDescending(s => s.f活動瀏覽次數);
                    break;
                case "LikeUp":
                    article = article.OrderBy(s => s.f活動讚數);
                    break;
                case "LikeDown":
                    article = article.OrderByDescending(s => s.f活動讚數);
                    break;
                default:
                    article = article.OrderBy(s => s.f活動標題);
                    break;
            }



            int currentPage = page < 1 ? 1 : page;

           
            //var articleList = article.ToList();
            var result = article.ToPagedList(currentPage, pagesize);


            return View(result);


        }

        public ActionResult personalIndex (int? id, string txtKey, string currentfilter , int page = 1)
        {


            var article = from t in (new dbJoutaEntities()).tActivity
                          where t.f活動類型 == "文章" && t.f會員編號 == id
                          orderby t.f會員編號 descending
                          select t;
            if (txtKey != null)
            {

                page = 1;


            }

            else
            {
                txtKey = currentfilter;

            }

            if (string.IsNullOrEmpty(txtKey))
            {

                 article = from t in (new dbJoutaEntities()).tActivity
                              where t.f活動類型 == "文章" && t.f會員編號 == id
                              orderby t.f活動編號 descending
                              select t;
            }

            else
            {

                article = from t in (new dbJoutaEntities()).tActivity
                          where t.f活動類型 == "文章" && t.f會員編號 == id && t.f活動標題.Contains(txtKey)
                          orderby t.f活動編號 descending
                          select t;

            }


            int currentPage = page < 1 ? 1 : page;


            var articleList = article.ToList();

            if (articleList.Count < 1)
            {
                RedirectToAction("personalIndex", new { id = id, page = 1 });
            }

            
            var result = articleList.ToPagedList(currentPage, pagesize);


            return View(result);
        }
        public ActionResult BlogContent(int? id)
        {

            var article = from t in (new dbJoutaEntities()).tActivity
                          where t.f活動類型 == "文章"&&t.f活動編號==id
                          select t;


            dbJoutaEntities db = new dbJoutaEntities();
            var target = db.tActivity.Where(t => t.f活動編號 == id).FirstOrDefault();
            target.f活動瀏覽次數 += 1;
            db.SaveChanges();


            return View(article.FirstOrDefault());


        }



        public ActionResult LikeIt(int? id)
        {
            var article = from t in (new dbJoutaEntities()).tActivity
                          where t.f活動類型 == "文章" && t.f活動編號 == id
                          select t;

            dbJoutaEntities db = new dbJoutaEntities();
            var target = db.tActivity.Where(t => t.f活動編號 == id).FirstOrDefault();
            target.f活動讚數 += 1;
            db.SaveChanges();

            return RedirectToAction("BlogContent",new { id = id }) ;
        }


        public ActionResult Create()
        {

            return View();

        }


        [HttpPost]
        public ActionResult Create(CBlog p)
        {
            
            HttpPostedFileBase blogPhoto = Request.Files["blogPhoto"];
            if (p.blogPhoto != null)
            {
                string photName = Guid.NewGuid().ToString() + Path.GetExtension(p.blogPhoto.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/images/"), photName);
                p.blogPhoto.SaveAs(path);
                p.f活動團圖 =  photName;
            }



            tActivity article = new tActivity();

            article.f活動類型 = "文章";
            article.f活動標題 = p.txtTitle;
            article.f活動地點 = p.txtLocation;
            article.f活動內容 = p.txtContent;
            article.f活動團圖 = p.f活動團圖;
            article.fQRcode網址 = p.QRcode;
            article.fQRcodeImage = p.QRcodeImage;
            article.f活動發起日期 = (DateTime.Now).ToString("yyyy-MM-dd HH:mm:ss");
            article.f活動地區 = p.f活動地區;
            article.f活動瀏覽次數 = 0;
            article.f活動讚數 = 0;

            var LoginMember = (tMember)Session["member"];
            article.f會員編號 = LoginMember.f會員編號;


            if (article != null)
            {

            dbJoutaEntities db = new dbJoutaEntities();
            db.tActivity.Add(article);
            db.SaveChanges();

               return RedirectToAction("index");

            }

            else
            {

                return RedirectToAction("index");

            }
 
    

        }


        [HttpPost]
        public ActionResult AddComment (CBlogComment p )
        {



            var ct = DateTime.Now;

            var CurrentTime = ct.ToString();



            var coomment = new tBlogComment()
            {

                f活動編號 = p.f活動編號,
                fBlogComment = p.Content,
                fCreateDate = CurrentTime,

            };


            db.tBlogComment.Add(coomment);
            db.SaveChanges();


            return RedirectToAction("BlogContent", new { id = p.f活動編號});


        }




        public ActionResult QRcode(int? id)
        {
            var article = from t in (new dbJoutaEntities()).tActivity
                          where t.f活動類型 == "文章" && t.f活動編號 == id
                          select t;
            var writer = new BarcodeWriter
            {
                Format = BarcodeFormat.QR_CODE,
                Options = new QrCodeEncodingOptions
                {
                    Height = 100,
                    Width = 100,
                }
            };


            if (article.Select(t => t.fQRcode網址).FirstOrDefault() != null)
            {

            var img = writer.Write(article.Select(t => t.fQRcode網址).FirstOrDefault());
            string FileName = article.Select(t => t.fQRcodeImage).FirstOrDefault();
            Bitmap myBitmap = new Bitmap(img);
            string filepath = string.Format(Server.MapPath("~/Content/images/") + "{0}.bmp", FileName);

            ViewBag.filePath = filepath;

            myBitmap.Save(filepath, ImageFormat.Bmp);
            ViewBag.IMG = myBitmap;


            }

            else
            {
                var img = writer.Write("https://www.iii.org.tw/");
                string FileName = "iii";
                Bitmap myBitmap = new Bitmap(img);
                string filepath = string.Format(Server.MapPath("~/Content/images/") + "{0}.bmp", FileName);

                ViewBag.filePath = filepath;

                myBitmap.Save(filepath, ImageFormat.Bmp);
                ViewBag.IMG = myBitmap;



            }



            return View();
        }

        public ActionResult PhotoGet(int? id)
        {
            var article = from t in (new dbJoutaEntities()).tActivity
                          where t.f活動類型 == "文章" && t.f活動編號 == id
                          select t;


            if (article.Select(t => t.fQRcodeImage).FirstOrDefault() != null)
            {

            string FileName = article.Select(t => t.fQRcodeImage).FirstOrDefault(); 

IIIProject_MVC_Travel/IIIProject_travel/Controllers/LoginController.cs
using IIIProject_travel.Security;
using IIIProject_travel.Services;
using IIIProject_travel.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Security;

namespace IIIProject_travel.Controllers
{
    public class LoginController : Controller
    {
        //宣告service物件
        private readonly MembersService membersService = new MembersService();
        //宣告寄信用service物件
        private readonly MailService mailService = new MailService();

        // GET: Login
        [AllowAnonymous]    //是人皆可進
        public ActionResult LoginIndex()
        {
            CLogin c = new CLogin();
            c.txtRememberMe = "記住我";
            return View(c);
        }

        [HttpPost]
        public ActionResult LoginIndex(CLogin user)
        {
            
            if (user.txtEmail == "admin" && user.txtPassword == "admin")
                return RedirectToAction("Home", "後台Home");
            string ValidateStr = membersService.LoginCheck(user.txtEmail,user.txtPassword);
            if (string.IsNullOrEmpty(ValidateStr))
            {
                tMember target = (new dbJoutaEntities()).tMember
                .FirstOrDefault(a => a.f會員電子郵件 == user.txtEmail && a.f會員密碼 == user.txtPassword);
                Session["member"] = target;
                return RedirectToAction("Home", "Home");
            }
            else
            {
                ModelState.AddModelError("txtPassword","密碼輸入錯誤");
                return View();
            }
        }

        //Logout
        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            string cookieName = WebConfigurationManager.AppSettings["CookieName"].ToString();
            //清除cookie
            HttpCookie cookie = new HttpCookie(cookieName);
            cookie.Expires = DateTime.Now.AddDays(-1);
            cookie.Values.Clear();
            Response.Cookies.Set(cookie);
            return RedirectToAction("LoginIndex");
        }
    }
}

IIIProject_MVC_Travel/IIIProject_travel/Controllers/ProfileController.cs
using IIIProject_travel.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IIIProject_travel.Controllers
{
    public class ProfileController : Controller
    {
        dbJoutaEntities db = new dbJoutaEntities();
        // GET: Profile
        
        public ActionResult ProfileIndex(string coupon)
        {
            CMember c = new CMember();
            DateTime date = DateTime.Now;
            ViewBag.Date = date;
            var travel = from t in (new dbJoutaEntities()).tActivity
                         select t;  //從資料表抓資料
            c.tActivities = travel;
            var x = (tMember)Session["member"];
            c.tMembers = db.tMember.Where(a=>a.f會員編號 == x.f會員編號).FirstOrDefault();
            return View(c);
        }
        [HttpPost]
        public ActionResult UploadImg(tMember t)
        {
            dbJoutaEntities db = new dbJoutaEntities();
            var x = db.tMember.Where(a => a.f會員編號 == t.f會員編號).FirstOrDefault();
            HttpPostedFileBase avaPhoto = Request.Files["f會員大頭貼"];
            if ( avaPhoto != null)
            {
                string photName = Guid.NewGuid().ToString() + Path.GetExtension(avaPhoto.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/images/"), photName);
                avaPhoto.SaveAs(path);
                x.f會員大頭貼 = photName;
            }
            db.SaveChanges();
            return RedirectToAction("ProfileIndex");
        }


        public ActionResult Save()
        {
            tMember y = (tMember)Session["member"];
            var x = db.tMember.Where(a=>a.f會員編號 == y.f會員編號).FirstOrDefault();
            x.f會員名稱 = Request.Form["txtName"];
            x.f會員暱稱 = Request.Form["txtNickName"];
            x.f會員生日 = Request.Form["txtBirth"];
            x.f會員興趣 = Request.Form["txtHobby"];
            x.f會員自我介紹 = Request.Form["txtIntro"];
            
            db.SaveChanges();
            ViewBag.msg = "資料修改成功";
            return RedirectToAction("ProfileIndex");
        }

        public ActionResult Chat(int? id)
        {
            CMember c = new CMember();
            var z = (tMember)Session["member"];
            if (z != null)
            {
                if (z.f會員編號 == id)
                {
                    var user = db.tMember.Where(x => x.f會員編號 == id).FirstOrDefault();
                    z.f會員編號 = user.f會員編號;
                    return View(z);
                }
            }
            var member = db.tMember.Where(x => x.f會員編號 == id).FirstOrDefault();
            c.tMembers = member;
            return View(c);
        }
        public ActionResult otherprofile(int? id)
        {
            CMember c = new CMember();
            var y = (tMember)Session["member"];
            if (y != null)      //需先判斷是否有登入資料，否則會報錯
            {
                if (y.f會員編號 == id)
                {
                    return RedirectToAction("ProfileIndex");
                }
            }
            
            var travel = from t in (new dbJoutaEntities()).tActivity
                             where t.f會員編號 == id
                             select t;  //從資料表抓資料
                var member = (new dbJoutaEntities()).tMember.Where(x => x.f會員編號 == id).FirstOrDefault();
            member.f瀏覽人數 += 1;
                c.tActivities = travel;
                c.tMembers = member;
                return View(c);  
        }

    }
}

IIIProject_MVC_Travel/IIIProject_travel/Views/Home/About.cshtml
@{ 
    Layout = null;
    var x = (tMember)Session["member"];
}
   

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>關於我們 | Jouta</title>
    @Styles.Render("~/Content/css/bootstrap.min.css")
    @Styles.Render("~/Content/sass/style.css")
    @Styles.Render("~/Content/css/關於我們.css")
</head>

<body class="b2">

    <div class="container-fluid">

        <!-- navbar -->
        <nav class="navbar navbar-expand-lg navbar-fixed-top" id="main">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Home", "Home")">
                    @*改用Url.Action*@
                    <img src="~/Content/images/joutalogo_black.png" alt="" width="100">
                </a>
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse justify-content-between" id="navbarNav">
                    <ul class="nav navbar-nav">
                        <li class="nav-item active">@Html.ActionLink("首頁", "Home", "Home", new { }, new { @class = "nav-link nav-main text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("找飯局", "EatIndex", "Eat", new { }, new { @class = "nav-link nav-eat text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("找旅遊", "TravelIndex", "Travel", new { }, new { @class = "nav-link nav-travel text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("找文章", "Index", "Blog", new { }, new { @class = "nav-link nav-blog text-dark" })</li>
                    </ul>
                    <ul class="nav navbar-nav">

                        <li class="nav-item">@Html.ActionLink("關於我們", "About", "Home", new { }, new { @class = "nav-link nav-register text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("聯絡我們", "New", "聯絡我們", new { }, new { @class = "nav-link nav-login text-dark" })</li>
                        @if (Session["member"] != null)
                        {


                            <li class="nav-item nav-link nav-login text-dark">@Html.ActionLink("您好，" + x.f會員名稱, "ProfileIndex", "Profile") </li>

                            <li class="nav-item">@Html.ActionLink("登出", "Home", "Home", new { id = 0 }, new { @class = "nav-link nav-login text-dark" })</li>
                        }
                        else
                        {


                            <li class="nav-item">@Html.ActionLink("登入", "LoginIndex", "Login", new { }, new { @class = "nav-link nav-login text-dark" })</li>

                            <li class="nav-item">@Html.ActionLink("註冊", "Register", "Home", new { }, new { @class = "nav-link nav-register text-dark" })</li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner banner">
            <div class="carousel-item active x">
                <img src="~/Content/images/homeabout5.jpg" class="d-block imgslide" alt="...">
            </div>
            <div class="carousel-item x banner">
                <img src="~/Content/images/1_臺北商圈吃玩買.jpg" class=" d-block imgslide" alt="...">
            </div>
        </div>
    </div>
    <div class="t1 fadeIn">
        <h2>交際新曲線 揪趴在身邊</h2>
        <p>Jouta成立於民國109年，總公司位於台北精華地段，提供消費者最方便的使用者體驗諮詢。</p>
        <p>成立以來一直秉持「交際無邊界」的理念，服務每一位使用者，建立起Jouta的好口碑。</p>
        <p>精英團隊的努力，專業態度和資深實力，備受各界的期待，</p>
        <p>使國人一提到關係，就想到「Jouta」；期許三年內成為台灣最大、最具規模的社會交際平台。</p>
    </div>

    <div class="container t2 shadow-lg p-3 mb-5 rounded">
        <div class="row">
            <hr>
            <div>
                <div class="block">
                    <img src="~/Content/images/關於我們(2).jpg" class="card-img-top img1 align-left slide-in" alt="">

                    <h2>
                        公司介紹
                        <span class="text-muted"></span>
                    </h2>
                    <p>
                        Jouta是一款社交應用平台，常用於約會與出遊。在該應用中，使用者可以隨機開立活動以及加團，在此款應用平台中，最使人心動的地方，即是平台上所提供的功能遠遠超出了僅僅揪團的行程，
                        還可以在上面發文，表達自己的心情感受以及出團經驗；這些功能，使平台含有社會化媒體的作用。
                    </p>
                </div>


            </div>

            <hr>
            <div>
                <div class="block d-flex">
                    <div>
                        <h2>
                            Corporate Culture
                            <span class="text-muted"></span>
                        </h2>
                        <p>
                            在基姆．卡麥隆〔Kim Cameron〕教授的分析架構中發現，偏好穩定的公司會偏向於強化階層制度；然而，在我們Jouta公司的企業文化中最注重的是創新、開放、多元，公司不相信必須要使用階級制度來控制員工，因為這樣可以有效的使員工適應環境甚至是製造屬於自己喜歡的工作環境，才能對公司穩定創造更長期的業務。
                        </p>
                    </div>
                    <img src="~/Content/images/關於我們(3).jpg" class="card-img-top img2  align-right slide-in" alt="">

                </div>
            </div>
            <hr>
            <div class="">
                <div class="block">
                    <img src="~/Content/images/關於我們(1).png" class="card-img-top img1 align-left slide-in" alt="">
                    <h2>
                        創新
                        <span class="text-muted"></span>
                    </h2>
                    <p>
                        「不創新，就等死！」（Innovate or die），是管理學之父彼得杜拉克的名言，努力不懈創造各種客製化功能以及揪團體驗；我們相信「經營社群」與「產品創新」是密不可分，同時也是條漫漫長路，需要用時間與誠意培養，絕對沒有一步到位的捷徑。
                    </p>
                </div>
            </div>
        </div>
    </div>


    <div class="t4">
        <div class="">
            <div class="row">
                <div class="col-sm " style="text-align:center;">
                    <img src="~/Content/images/gps.png" alt="" width="200">
                    <h2>服務據點</h2>
                </div>
                <div class="col-sm">
                    <h4>資訊工業策進會</h4>
                    <h5>台北公司</h5>
                    <p>服務專線：(02)27089215</p>
                    <p>10658台北市大安區信義路三段153號11樓</p>

                </div>
                <div class="col-sm">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3615.011147857099!2d121.54038681537861!3d25.033695744456786!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442abd4825ecdf1%3A0xa9479a36fc6b99d0!2sDigital%20Education%20Institute%2C%20III!5e0!3m2!1szh-TW!2stw!4v1600151782083!5m2!1szh-TW!2stw"
                            width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
                    </iframe>

                </div>
            </div>
        </div>

    </div>
    <!-- footer -->
    <div class="container-fluid footer">
        <p class="text-center mt-2 mb-2" style="font-size:16px;">Copyright © 2020 Jouta All rights reserved</p>
    </div>

    <!-- script -->
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/IIIProject/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/IIIProject/navbar.js"></script>
    <script src="~/Scripts/IIIProject/debounce.js"></script>
</body>
</html>

IIIProject_MVC_Travel/IIIProject_travel/Views/Home/Register.cshtml
@model IIIProject_travel.ViewModel.CRegisterModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="zh-Hant-TW">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>註冊 | Jouta</title>
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/sass/style.css" rel="stylesheet" />
    <link href="~/Content/css/register.css" rel="stylesheet" />
    <link href="~/Content/fontawesome/css/all.css" rel="stylesheet" />
    <style>
        #eye,#eye1 {
            float:right;
            position:relative;
            bottom:30px;
            right:10px;
        }
    </style>
</head>

<body>
    <!-- header -->
    <div class="container-fluid">
        <!-- navbar -->
        <nav class="navbar navbar-expand-lg navbar-fixed-top">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Home", "Home")">
                    @*改用Url.Action*@
                    <img src="~/Content/images/joutalogo_black.png" alt="" width="100">
                </a>
                @*<div class="navbar-header" id="main">*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*</div>*@
                <div class="navbar-collapse collapse justify-content-between" id="navbarNav">
                    <ul class="nav navbar-nav">
                        <li class="nav-item active">@Html.ActionLink("首頁", "Home", "Home", new { }, new { @class = "nav-link nav-main text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("找飯局", "EatIndex", "Eat", new { }, new { @class = "nav-link nav-eat text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("找旅遊", "TravelIndex", "Travel", new { }, new { @class = "nav-link nav-travel text-dark" })</li>
                        <li class="nav-item">@Html.ActionLink("找文章", "Index", "Blog", new { }, new { @class = "nav-link nav-blog text-dark" })</li>
                    </ul>
                    <ul class="nav navbar-nav">
                            <li class="nav-item">@Html.ActionLink("登入", "LoginIndex", "Login", new { }, new { @class = "nav-link nav-login text-dark" })</li>
                            <li class="nav-item">@Html.ActionLink("註冊", "Register", "Home", new { }, new { @class = "nav-link nav-register text-dark" })</li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <!-- main -->
    <div class="container cMain">
        <div class="row">
            <div class="col-md-12 offset=md-1">
                <div class="row">
                    <div class="col-sm-7 col-md-5 register-left">
                        <a href="@Url.Action("Home", "Home")"><img src="~/Content/images/joutalogo_black.png"></a>
                        <h3>立即加入</h3>
                        <p>Join Us</p>
                    </div>
                    <div class="col-sm-5 col-md-7 register-right">
                        <h2 id="xx">會員註冊</h2>

                        @using (Html.BeginForm())
                        {
                           @Html.AntiForgeryToken()
                            <div class="register-form">
                                @Html.ValidationSummary(true,"",new {@class="text-danger" })
                                <div class="form-group">
                                    <input type="text" name="txtEmail" class="form-control" placeholder="信箱" id="email">
                                    @Html.ValidationMessageFor(model=>model.txtEmail,"",new { @class="text-danger"})
                                </div>

                                <div class="form-group">
                                    <input type="text" name="txtNickname" class="form-control" placeholder="使用者名稱" id="name">
                                    @Html.ValidationMessageFor(model => model.txtNickname, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <input type="password" name="txtPassword" class="form-control" placeholder="密碼" id="password"><span id="eye"><i class="fas fa-eye"></i></span>

                                    <span style="color:	#BEBEBE;">*請輸入6位以上包含英文與數字的密碼</span><br />
                                    @Html.ValidationMessageFor(model => model.txtPassword, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <input type="password" name="txtPassword_confirm" class="form-control" placeholder="再次輸入密碼" id="password_confirm"><span id="eye1"><i class="fas fa-eye"></i></span>
                                    @Html.ValidationMessageFor(model => model.txtPassword_confirm, "", new { @class = "text-danger" })
                                </div>
                                <div class="d-flex justify-content-between">
                                    <button type="submit" class="btn btn-warning">註冊</button>
                                    <button type="reset" class="btn btn-dark">清除</button>
                                </div>
                               
                            </div>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- footer -->
    <div class="container-fluid footer">
        <p class="text-center mt-2 mb-2">&copy; @DateTime.Now.Year Jouta All rights reserved</p>
    </div>
    <!-- script -->
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/IIIProject/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @*匯入驗證用的js*@
    @section Scripts{
        @Scripts.Render("~/bundles/jqueryval")
    }
<script>
    $("#xx").click(function () {
        $("#email").val("pikaqiu193@gmail.com");
        $("#name").val("皮卡丘");
        $("#password").val("a123456");
        $("#password_confirm").val("a123456");
    });


    $('#eye').click(function () {
        icon = $(this).find("i");
        if (icon.hasClass("fa-eye")) {
            $("#password").attr("type","text");
            icon.addClass("fa-eye-slash").removeClass("fa-eye");
        } else {
            $("#password").attr("type", "password");
            icon.addClass("fa-eye").removeClass("fa-eye-slash");
        }
    }) 

    $('#eye1').click(function () {
        icon = $(this).find("i");
        if (icon.hasClass("fa-eye")) {
            $("#password_confirm").attr("type", "text");
            icon.addClass("fa-eye-slash").removeClass("fa-eye");
        } else {
            $("#password_confirm").attr("type", "password");
            icon.addClass("fa-eye").removeClass("fa-eye-slash");
        }
    }) 

</script>
</body>

</html>