IIIProject_MVC_Travel/IIIProject_travel/Controllers/優惠發送Controller.cs
using IIIProject_travel.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace IIIProject_travel.Controllers
{
    public class 優惠發送Controller : Controller
    {
        // GET: 優惠發送
        public ActionResult List()
        {
            return View();
        }

        [HttpPost]
        public ActionResult List(string randLocation)
        {

            dbJoutaEntities db = new dbJoutaEntities();

            var x = (from t in db.tMember
                     //where (t.f會員緯度 < curLat+0.02 && 
                     //t.f會員緯度 > curLat - 0.02 &&
                     //t.f會員經度 < curLng + 0.02 &&
                     //t.f會員經度 > curLng - 0.02)
                     select new
                     {
                         mMemberNum = t.f會員編號,
                         mEmail = t.f會員電子郵件,
                         mName = t.f會員名稱,
                         mRating = t.f會員評分
                     })
                    .OrderBy(t => Guid.NewGuid()).Take(1);

            return Json(x, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SendMail(string txtCouponInfo, string memberId1)
        {
            dbJoutaEntities db = new dbJoutaEntities();

            var x = db.tMember.Where(a => a.f會員帳號 == memberId1.ToString()).FirstOrDefault();

            string randCode = Guid.NewGuid().ToString();

            //Jouta官方帳號
            string gmail_account = "Joutagroup445@gmail.com";
            string gmail_password = "admin123admin";
            string gmail_mail = "Joutagroup445@gmail.com";     //gmail信箱

            //var verifyUrl = "/Home/ResetPassword/" + randCode;
            //var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress(gmail_mail, "Jouta服務團隊");
            var toEmail = new MailAddress(x.f會員電子郵件);
            string body = "您好，<br/><br/>恭喜您抽到：" + txtCouponInfo +
            "<br/><br/>優惠代碼請至該店家網站或其門市兌換使用：" + randCode + "，使用期限至9/30，請盡速使用!</a>";

            SmtpClient smtpServer = new SmtpClient("smtp.gmail.com");
            smtpServer.Port = 587;
            smtpServer.Credentials = new System.Net.NetworkCredential(gmail_account, gmail_password);
            //開啟SSL
            smtpServer.EnableSsl = true;

            MailMessage mail = new MailMessage();
            //設定來源信箱
            mail.From = new MailAddress(gmail_mail);
            //設定收信者信箱
            mail.To.Add(toEmail);
            //主旨
            mail.Subject = "Jouta 優惠好禮 !";
            //內容
            mail.Body = body;
            //設定信箱內容為HTML格式
            mail.IsBodyHtml = true;
            smtpServer.Send(mail);

            return RedirectToAction("List");
        }
    }
}

IIIProject_MVC_Travel/IIIProject_travel/Controllers/後台文章Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace IIIProject_travel.Controllers
{
    public class 後台文章Controller : Controller
    {
        // GET: 後台文章
        public ActionResult List(string date起日, string dateStartFilter, string date迄日, string dateEndFiler, string sortOrder, string txt關鍵字, string currentFilter, int page = 1)
        {

            //搜尋
            var 文章 = from m in (new dbJoutaEntities()).tActivity
                     where m.f活動類型 == "文章"
                     select m;

            if (txt關鍵字 != null && date起日 != null && date迄日 != null)
            {
                page = 1;
            }
            else
            {
                txt關鍵字 = currentFilter;
                date起日 = dateStartFilter;
                date迄日 = dateEndFiler;
            }

            if (string.IsNullOrEmpty(txt關鍵字))
            {
                文章 = from m in (new dbJoutaEntities()).tActivity
                     where m.f活動類型 == "文章"
                     select m;
                if (!string.IsNullOrEmpty(date起日) && !string.IsNullOrEmpty(date迄日))
                    文章 = from p in 文章
                         where (string.Compare(p.f活動發起日期.Substring(0, 10), date起日) >= 0) &&
                               (string.Compare(p.f活動發起日期.Substring(0, 10), date迄日) <= 0)
                         select p;
            }

            else
            {
                文章 = from m in 文章
                     where m.f活動類型.Contains("文章") &&
                            (string.Compare(m.f活動發起日期.Substring(0, 10), date起日) >= 0) &&
                            (string.Compare(m.f活動發起日期.Substring(0, 10), date迄日) <= 0) &&
                           m.f活動編號.ToString().Contains(txt關鍵字) || m.f活動標題.Contains(txt關鍵字) ||
                           m.f活動標籤.Contains(txt關鍵字) || m.f活動內容.Contains(txt關鍵字) ||
                           m.f活動團圖.Contains(txt關鍵字) || m.f活動地區.Contains(txt關鍵字) ||
                           m.f活動地點.Contains(txt關鍵字) || m.f活動所屬.Contains(txt關鍵字) ||
                           m.f活動招募截止時間.Contains(txt關鍵字) || m.f活動分類.Contains(txt關鍵字) ||
                           m.f活動留言.Contains(txt關鍵字) || m.f活動留言時間.Contains(txt關鍵字) ||
                           m.f活動發起日期.Contains(txt關鍵字) || m.f活動結束時間.Contains(txt關鍵字) ||
                           m.f活動開始時間.Contains(txt關鍵字)
                     select m;
            }

            //排序 降冪和升冪
            ViewBag.當前搜尋 = txt關鍵字;
            ViewBag.當前起日 = date起日;
            ViewBag.當前迄日 = date迄日;
            ViewBag.標題排序 = string.IsNullOrEmpty(sortOrder) ? "標題降冪" : "";
            ViewBag.編號排序 = sortOrder == "編號升冪" ? "編號降冪" : "編號升冪";
            ViewBag.帳號排序 = sortOrder == "帳號升冪" ? "帳號降冪" : "帳號升冪";
            ViewBag.內容排序 = sortOrder == "內容升冪" ? "內容降冪" : "內容升冪";
            ViewBag.建立時間排序 = sortOrder == "建立時間升冪" ? "建立時間降冪" : "建立時間升冪";
            ViewBag.地區排序 = sortOrder == "地區升冪" ? "地區降冪" : "地區升冪";

            switch (sortOrder)
            {
                case "標題降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動標題);
                    break;
                case "編號降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動編號);
                    break;
                case "編號升冪":
                    文章 = 文章.OrderBy(s => s.f活動編號);
                    break;
                case "帳號降冪":
                    文章 = 文章.OrderByDescending(s => s.f會員編號);
                    break;
                case "帳號升冪":
                    文章 = 文章.OrderBy(s => s.f會員編號);
                    break;
                case "內容降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動內容);
                    break;
                case "內容升冪":
                    文章 = 文章.OrderBy(s => s.f活動內容);
                    break;
                case "建立時間降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動發起日期);
                    break;
                case "建立時間升冪":
                    文章 = 文章.OrderBy(s => s.f活動發起日期);
                    break;
                case "地區降冪":
                    文章 = 文章.OrderByDescending(s => s.f活動地區);
                    break;
                case "地區升冪":
                    文章 = 文章.OrderBy(s => s.f活動地區);
                    break;

                default:
                    文章 = 文章.OrderBy(s => s.f活動標題);
                    break;
            }



            //分頁
            int 筆數 = 20;
            int 當前頁面 = page < 1 ? 1 : page;
            var 結果 = 文章.ToPagedList(當前頁面, 筆數);

            return View(結果);
        }



        public ActionResult d刪除(int? id)
        {
            if (id == null)
                RedirectToAction("List");

            tActivity x = new tActivity();
            dbJoutaEntities db = new dbJoutaEntities();
            x = db.tActivity.FirstOrDefault(m => m.f活動編號 == id);
            db.tActivity.Remove(x);
            db.SaveChanges();

            return RedirectToAction("List");

        }
        public ActionResult v查看(int? id)
        {
            if (id == null)
                RedirectToAction("List");

            dbJoutaEntities db = new dbJoutaEntities();
            tActivity x = new tActivity();
            x = db.tActivity.FirstOrDefault(m => m.f活動編號 == id);

            return View(x);
        }


    }
}

IIIProject_MVC_Travel/IIIProject_travel/Controllers/聯絡我們Controller.cs
using IIIProject_travel.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Net.Mail;

namespace IIIProject_travel.Controllers
{
    public class 聯絡我們Controller : Controller
    {
        //GET: 聯絡我們
        public ActionResult List(string date起日, string dateStartFilter, string date迄日, string dateEndFiler, string sortOrder, string txt關鍵字, string currentFilter, int page = 1)
        {
            var 意見 = from m in (new dbJoutaEntities()).tComment
                     select m;

            if (txt關鍵字 != null && date起日 != null && date迄日 != null)
            {
                page = 1;
            }
            else
            {
                txt關鍵字 = currentFilter;
                date起日 = dateStartFilter;
                date迄日 = dateEndFiler;
            }

            if (string.IsNullOrEmpty(txt關鍵字))
            {
                意見 = from m in (new dbJoutaEntities()).tComment
                     select m;
                if (!string.IsNullOrEmpty(date起日) && !string.IsNullOrEmpty(date迄日))
                    意見 = from p in 意見
                         where (string.Compare(p.f意見時間.Substring(0, 10), date起日) >= 0) &&
                               (string.Compare(p.f意見時間.Substring(0, 10), date迄日) <= 0)
                         select p;
            }

            else
            {
                意見 = from m in 意見
                     where (string.Compare(m.f意見時間.Substring(0, 10), date起日) >= 0) &&
                            (string.Compare(m.f意見時間.Substring(0, 10), date迄日) <= 0) &&
                           m.fID.ToString().Contains(txt關鍵字) || m.f標題.Contains(txt關鍵字) ||
                           m.f性別.Contains(txt關鍵字) || m.f意見.Contains(txt關鍵字) ||
                           m.f意見類型.Contains(txt關鍵字) || m.f聯絡人.Contains(txt關鍵字) ||
                           m.f電子郵件.Contains(txt關鍵字) || m.f電話.Contains(txt關鍵字)||
                           m.f意見狀態.Contains(txt關鍵字)
                     select m;
            }

            //排序 降冪和升冪
            ViewBag.當前搜尋 = txt關鍵字;
            ViewBag.當前起日 = date起日;
            ViewBag.當前迄日 = date迄日;
            ViewBag.名稱排序 = string.IsNullOrEmpty(sortOrder) ? "標題降冪" : "";
            ViewBag.編號排序 = sortOrder == "編號升冪" ? "編號降冪" : "編號升冪";
            ViewBag.聯絡人排序 = sortOrder == "聯絡人升冪" ? "聯絡人降冪" : "聯絡人升冪";
            ViewBag.內容排序 = sortOrder == "內容升冪" ? "內容降冪" : "內容升冪";
            ViewBag.建立時間排序 = sortOrder == "建立時間升冪" ? "建立時間降冪" : "建立時間升冪";
            ViewBag.分類排序 = sortOrder == "分類升冪" ? "分類降冪" : "分類升冪";
            ViewBag.性別排序 = sortOrder == "性別升冪" ? "性別降冪" : "性別升冪";
            ViewBag.電子郵件排序 = sortOrder == "電子郵件升冪" ? "電子郵件降冪" : "電子郵件升冪";
            ViewBag.電話排序 = sortOrder == "電話升冪" ? "電話降冪" : "電話升冪";
            ViewBag.狀態排序 = sortOrder == "狀態升冪" ? "狀態降冪" : "狀態升冪";


            switch (sortOrder)
            {
                case "標題降冪":
                    意見 = 意見.OrderByDescending(s => s.f標題);
                    break;
                case "編號降冪":
                    意見 = 意見.OrderByDescending(s => s.fID);
                    break;
                case "編號升冪":
                    意見 = 意見.OrderBy(s => s.fID);
                    break;
                case "聯絡人降冪":
                    意見 = 意見.OrderByDescending(s => s.f聯絡人);
                    break;
                case "聯絡人升冪":
                    意見 = 意見.OrderBy(s => s.f聯絡人);
                    break;
                case "內容降冪":
                    意見 = 意見.OrderByDescending(s => s.f意見);
                    break;
                case "內容升冪":
                    意見 = 意見.OrderBy(s => s.f意見);
                    break;
                case "建立時間降冪":
                    意見 = 意見.OrderByDescending(s => s.f意見時間);
                    break;
                case "建立時間升冪":
                    意見 = 意見.OrderBy(s => s.f意見時間);
                    break;
                case "分類降冪":
                    意見 = 意見.OrderByDescending(s => s.f意見類型);
                    break;
                case "分類升冪":
                    意見 = 意見.OrderBy(s => s.f意見類型);
                    break;
                case "性別降冪":
                    意見 = 意見.OrderByDescending(s => s.f性別);
                    break;
                case "性別升冪":
                    意見 = 意見.OrderBy(s => s.f性別);
                    break;
                case "電子郵件降冪":
                    意見 = 意見.OrderByDescending(s => s.f電子郵件);
                    break;
                case "電子郵件升冪":
                    意見 = 意見.OrderBy(s => s.f電子郵件);
                    break;
                case "電話降冪":
                    意見 = 意見.OrderByDescending(s => s.f電話);
                    break;
                case "電話升冪":
                    意見 = 意見.OrderBy(s => s.f電話);
                    break;
                case "狀態降冪":
                    意見 = 意見.OrderByDescending(s => s.f意見狀態);
                    break;
                case "狀態升冪":
                    意見 = 意見.OrderBy(s => s.f意見狀態);
                    break;


                default:
                    意見 = 意見.OrderBy(s => s.f標題);
                    break;
            }


            int 筆數 = 20;
            int 當前頁面 = page < 1 ? 1 : page;
            var 結果 = 意見.ToPagedList(當前頁面, 筆數);

            return View(結果);

        }
        public ActionResult d刪除(int? id)
        {
            if (id == null)
                RedirectToAction("List");

            tComment x = new tComment();
            dbJoutaEntities db = new dbJoutaEntities();
            x = db.tComment.FirstOrDefault(m => m.fID == id);
            db.tComment.Remove(x);
            db.SaveChanges();

            return RedirectToAction("List");

        }
        public ActionResult r回覆(int? id)
        {
            if (id == null)
                RedirectToAction("List");

            dbJoutaEntities db = new dbJoutaEntities();
            tComment x = new tComment();
            x = db.tComment.FirstOrDefault(m => m.fID == id);

            return View(x);
        }
        [HttpPost]
        public ActionResult r回覆(C回覆 y,tComment p)
        {
            send(y);
            //ViewBag.kk = "傳送成功";
            dbJoutaEntities db = new dbJoutaEntities();
            tComment A = db.tComment.FirstOrDefault(m => m.fID == p.fID);
            if (A != null)
            {
                A.f意見狀態 = "已回覆";
                db.SaveChanges();
            }
                return RedirectToAction("List");
        }



        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(C回覆 y)
        {
            dbJoutaEntities db = new dbJoutaEntities();
            tComment x = new tComment();
            x.f標題 = Request.Form["f標題"];
            x.f意見 = Request.Form["f意見"];
            x.f性別 = Request.Form["f性別"];
            x.f意見類型 = Request.Form["f意見類型"];
            x.f聯絡人 = Request.Form["f聯絡人"];
            x.f電子郵件 = Request.Form["f電子郵件"];
            x.f電話 = Request.Form["f電話"];
            x.f意見時間 = DateTime.Now.ToString();
            x.f意見狀態 = "未回覆";
            db.tComment.Add(x);
            db.SaveChanges();
            string message = "傳送成功";
            ViewBag.ll =message;
            return View ();
        }



        [NonAction]
        public void send(C回覆 y)
        {
            //Jouta官方帳號
            string gmail_account = "Joutagroup445@gmail.com";
            string gmail_password = "admin123admin";
            string gmail_mail = "Joutagroup445@gmail.com";
            var fromEmail = new MailAddress(gmail_mail, "Jouta服務團隊");
            var toEmail = new MailAddress(y.f電子郵件);
            string body = "你好，"+ "&nbsp;" + y.f聯絡人 + "&nbsp;" + "Jouta團隊已收到您的意見:" + "<br/>" +
                          "<br/>" + y.f標題 + "<br/>"+ "<br/>" + y.f意見 + "<br/>"+"<br/>" +"在此向您說明:" + "<br/>"+ "<br/>"+ y.f回覆 + "<br/>"+ "<br/>"+
                          "<br/>"+ "<br/>"+"如有任何問題，歡迎隨時與我們聯繫，謝謝";
                         

            SmtpClient smtpServer = new SmtpClient("smtp.gmail.com");
            smtpServer.Port = 587;
            smtpServer.Credentials = new System.Net.NetworkCredential(gmail_account, gmail_password);
            //開啟SSL
            smtpServer.EnableSsl = true;

            MailMessage mail = new MailMessage();
            //設定來源信箱
            mail.From = new MailAddress(gmail_mail);
            //設定收信者信箱
            mail.To.Add(toEmail);
            //主旨
            mail.Subject = "Jouta意見回覆";
            //內容
            mail.Body = body;
            //設定信箱內容為HTML格式
            mail.IsBodyHtml = true;
            smtpServer.Send(mail);
      
        }


    }
}

IIIProject_MVC_Travel/IIIProject_travel/Views/聯絡我們/List.cshtml
@using PagedList
@using PagedList.Mvc
@{
    Layout = null;
}
@model IPagedList<IIIProject_travel.tComment>

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="">
    <title>意見列表 | Jouta Admin</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/Content/css/dashboard.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
        }

        #line {
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 300px;
            white-space: nowrap;
        }

        .table td, .table th {
            vertical-align: middle;
        }
    </style>

</head>

<body>

    @*navbar*@
    <form action="/聯絡我們/List" method="GET">
        <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="@Url.Action("Home","後台Home")">
                <img src="~/Content/images/joutalogo.png" width="14" class="mr-2" />Jouta Admin
            </a>
            <div>
                <span class="badge badge-secondary">建立起日：</span>
                <input type="date" name="date起日" />
            </div>
            <div>
                <span class="badge badge-secondary">建立迄日：</span>
                <input type="date" name="date迄日" />
            </div>
            <input type="text" placeholder="關鍵字" aria-label="Search" name="txt關鍵字" class="form-control form-control-dark w-100">
            <input type="submit" value="搜尋" class=" btn btn-secondary" />
            <ul class="navbar-nav px-3">
                <li class="nav-item text-nowrap">
                    <a>
                        @Html.ActionLink("Sign out", "Home", "Home", new { id = 0 }, new { @class = "nav-link" })
                    </a>
                </li>
            </ul>
        </nav>
    </form>

    @*sidebar*@
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Home","後台Home")">
                                <span data-feather="home"></span>
                                網站概覽
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","後台會員")">
                                <span data-feather="users"></span>
                                會員列表
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","後台旅遊")">
                                <span data-feather="file"></span>
                                旅遊列表
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","後台飯局")">
                                <span data-feather="bar-chart-2"></span>
                                飯局列表
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","後台文章")">
                                <span data-feather="layers"></span>
                                文章列表
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","聯絡我們")">
                                <span data-feather="message-square"></span>
                                意見列表　<
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("List","優惠發送")">
                                <span data-feather="gift"></span>
                                優惠發送
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            @*主內容*@
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <h2>意見列表</h2>
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <td>@Html.ActionLink("編號", "List", new { sortOrder = ViewBag.編號排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("標題", "List", new { sortOrder = ViewBag.標題排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("聯絡人", "List", new { sortOrder = ViewBag.聯絡人排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("建立時間", "List", new { sortOrder = ViewBag.建立時間排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("性別", "List", new { sortOrder = ViewBag.性別排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("電子郵件", "List", new { sortOrder = ViewBag.電子郵件排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("電話", "List", new { sortOrder = ViewBag.電話排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("分類", "List", new { sortOrder = ViewBag.分類排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("內容", "List", new { sortOrder = ViewBag.內容排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>@Html.ActionLink("狀態", "List", new { sortOrder = ViewBag.狀態排序, dateStartFilter = ViewBag.當前起日, dateEndFiler = ViewBag.當前迄日, currentFilter = ViewBag.當前搜尋 })</td>
                                <td>按鈕</td>
                                <td>按鈕</td>
                            </tr>
                        </thead>

                        <tbody>

                            @{
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.fID)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f標題)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f聯絡人)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f意見時間)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f性別)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f電子郵件)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f電話)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f意見類型)</td>
                                        <td id="line">@Html.DisplayFor(modelItem => item.f意見)</td>
                                        <td>@Html.DisplayFor(modelItem => item.f意見狀態)</td>

                                        <td>
                                            @Html.ActionLink("回覆", "r回覆", "聯絡我們", new { id = item.fID }, new { Class = "btn btn-info" })
                                        </td>
                                        <td>
                                            @Html.ActionLink("刪除", "d刪除", "聯絡我們", new { id = item.fID },
                                            new { OnClick = "return confirm('確定要刪除嗎?')", Class = "btn btn-danger" })
                                        </td>
                                    </tr>
                                }
                            }


                        </tbody>
                    </table>
                    @Html.PagedListPager(Model, page => Url.Action("List", new { page }))
                    @ViewBag.ll
                </div>
            </main>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Content/bootstrap-4.5.2-dist/js/bootstrap.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="~/Scripts/IIIProject/dashboard.js"></script>
</body>

</html>